/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yytec_javamain_jni_MaxValTest */

#ifndef _Included_com_yytec_javamain_jni_MaxValTest
#define _Included_com_yytec_javamain_jni_MaxValTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yytec_javamain_jni_MaxValTest
 * Method:    max
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_yytec_javamain_jni_MaxValTest_max
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_yytec_javamain_jni_MaxValTest
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_yytec_javamain_jni_MaxValTest_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
