/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yytec_javamain_MyThreadTest */

#ifndef _Included_com_yytec_javamain_MyThreadTest
#define _Included_com_yytec_javamain_MyThreadTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yytec_javamain_MyThreadTest
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yytec_javamain_MyThreadTest_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
