/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yytec_javamain_HelloNativeTest */

#ifndef _Included_com_yytec_javamain_HelloNativeTest
#define _Included_com_yytec_javamain_HelloNativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yytec_javamain_HelloNativeTest
 * Method:    sayHello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yytec_javamain_HelloNativeTest_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
